### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by sergeevabc** [palant/enforceencryption#11]
Dear @palant, could you explore the possibility of making your extension compatible with [Pale Moon](https://forum.palemoon.org/viewtopic.php?t=8740)?

**Comment by palant** [comment]
With Pale Moon developing modern standard unnecessary ballast? Rather unlikely.

**Comment by sergeevabc** [comment]
HTML is a standard whereas Jetpack or WebExtensions is not a standard, but a fleeting fashion. Pale Moon [welcomes XUL](https://www.palemoon.org/roadmap.shtml) for a reason. Since XUL could be used both by Firefox and Pale Moon users, then why not?

**Comment by palant** [comment]
Firefox is deprecating XUL, the plan is to remove it. There are plenty of reasons for that. Most importantly, XUL is an archaism - it was great in 1999 when it was conceived but it is largely superseded by HTML5 today. What's left is a huge compatibility burden with many small but important differences to modern HTML and very high barriers to entry. Also, letting extensions work on the open heart of the application cannot be considered a viable extension mechanism today. But of course Pale Moon is going to hold on to XUL until everything breaks apart - because their approach is preserving the status quo and avoiding hard choices.

This extension wasn't built on XUL for a reason. It was meant to be easy to contribute to as well as port to other platforms. So while the original version was running on Jetpack, it now supports Chrome and WebExtensions as alternative frameworks. It is also relies heavily on modern JavaScript features - such as promises which are unsupported by Pale Moon (planned at some unspecified point in future), or WebCrypto API which Pale Moon intentionally doesn't support. And that's merely the two things I can name immediately which are not supported by Pale Moon, I'm absolutely certain that there would be way more showstoppers if the port were ever attempted.

**Comment by mattatobin** [comment]
Your information is as out of date as you seem to think Pale Moon is. Our new Milestone which is close to being finalized fully supports ES6 promises and Web Crypto API (not that Web Crypto is sane mind you, but we support will it in v27).

XUL, XBL, et all are still fantastic technologies that we are proud to inherit, a legacy of freedom and choice that is the corner stone of Pale Moon.. Not never finished perpetual draft "standards" the committee made up of Google ,Microsoft, Adobe, and sometimes Mozilla that approved them for their own benefit not the benefit of users or the sham concept of the Open Web(tm).

Regardless, please check your facts before you insist others "check their privilege".
